server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Permite carregar tiles de domínios externos
    add_header Referrer-Policy "no-referrer-when-downgrade";
    add_header Cross-Origin-Resource-Policy "cross-origin";

    location / {
        try_files $uri $uri/ /index.html;
    }
}
